version : '3.7'

services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
        - "5432:5432"
    environment:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "password"
     volumes:
        -my_dbdata:/var/lib/postgresql/data