### 글생성
POST http://203.243.17.90:8003/api/post/post
Content-Type: application/json

{
  "title": "test",
  "content" : "test",
  "writer" : "admin@naver.com"
}

### 유저 생성
POST http://localhost:8003/api/user/register
Content-Type: application/json

{
  "email" : "admin@daum.net",
  "password" : "admin",
  "name" : "admin"
}

### 로그인
POST http://203.243.17.90:8003/api/user/login
Content-Type: application/json

{
  "email": "admin@naver.com",
  "password" : "admin"
}

### 글 수정
POST http://localhost:8003/api/post/postUpdate
Content-Type: application/json

{
  "id" : 1,
  "title": "test3",
  "content" : "test3"
}


### 글 삭제
POST http://localhost:8003/api/post/postDelete
Content-Type: application/json

{
  "id" : 1
}